POST http://localhost:3001/api/todos 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Iml2YW5hdGlhcyIsImlkIjoiNjMzMjdjYjVmMmUxZWMwYWYxNzUyYzEyIiwiaWF0IjoxNjY0NzQ1NTAzLCJleHAiOjE2NjUxNzc1MDN9.wwwdGQ-W8joERagDhf6an25u8EWEklinw9wgLwcznN0

{
  "title": "todo created with an authorization token!",
  "isPriority": true
}