DELETE http://localhost:3001/api/todos/633d153b0cfd4aff989230a4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2MzNkMTRhNjBjZmQ0YWZmOTg5MjMwOTQiLCJpYXQiOjE2NjQ5NDczNzYsImV4cCI6MTY2NTM3OTM3Nn0.469su-g_PRlpCrgyFEs3kGBGbxUUZJTVuTox-Gcar60
