GET http://localhost:3001/api/todos/usertodos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2MzNkMTRhNjBjZmQ0YWZmOTg5MjMwOTQiLCJpYXQiOjE2NjU0NTcxNjUsImV4cCI6MTY2NTg4OTE2NX0.fqwISNKQTN4PEV74SZFn1P1ZO7zQ_g8sxiJDfMi__rw
