PUT http://localhost:3001/api/todos/id=633a1c2235c65609d1573e89
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Iml2YW5hdGlhcyIsImlkIjoiNjMzMjdjYjVmMmUxZWMwYWYxNzUyYzEyIiwiaWF0IjoxNjY0NzUyMjYyLCJleHAiOjE2NjUxODQyNjJ9.k6Hc0iR-nm2MFOKE8bymUD_eEdPlrz2SpsQyJXCyew4

{
  "title": "I'm modifying this todo!",
  "isCompleted": true
}