PUT http://localhost:3001/api/todos/633d06ab6ecc56ae3d1bdcef
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Iml2YW5hdGlhcyIsImlkIjoiNjMzY2IxNjc5Yjc2YTI4NDNjOWY4NTBlIiwiaWF0IjoxNjY0OTIyMDA1LCJleHAiOjE2NjUzNTQwMDV9.uaZpr-P8CzqPu_DtoXPhNfwU0hmDnvUN_GwLbJbfWYk

{
  "title": "I'm modifying this todo!",
  "isCompleted": true
}